default: &default
  dispatchers:
    - polling_interval: 10
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 10

development:
  dispatchers:
    - polling_interval: 10
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 10

test:
  <<: *default

production:
  <<: *default
